---
# default
spring:
  profiles:
    default: dev
ncp:
  clova-studio:
    url: ${CLOVA_STUDIO_URL}
    api-gateway-key: ${CLOVA_API_GATEWAY_KEY}
    clova-studio-api-key: ${CLOVA_STUDIO_API_KEY}
    clova-studio-request-id: ${CLOVA_STUDIO_REQUEST_ID}
---
# prod
spring:
  profiles:
    active: prod
  docker:
    compose:
      enabled: false
  data:
    redis:
      host: redisc-k4fic.vpc-cdb.ntruss.com
      port: 6379
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
---
# dev
spring:
  profiles:
    active: dev
  docker:
    compose:
      enabled: true
      file: ./compose.yaml
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
